source "https://rubygems.org"
ruby "~> 3.2.0"

gem "rails", "~> 7.0"
gem "puma", "~> 6.0"
gem "mysql2", "~> 0.5"
gem "bcrypt", "~> 3.1"
gem "kaminari", "~> 1.2"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: [:windows, :mingw, :mswin, :x64_mingw]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "dotenv-rails"
end
